steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/bux-hw/bux-hw/what-time-is-it:latest', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/bux-hw/bux-hw/what-time-is-it:latest']

  - name: 'hashicorp/terraform'  
    args: ['init']
  
  - name: 'hashicorp/terraform'
    args: ['plan']

  - name: 'hashicorp/terraform'
    args: ['apply', "-auto-approve"]
    
options:
  logging: CLOUD_LOGGING_ONLY